### ISSUE TITLE
UX/UI: Display QR when claiming ecash

### ISSUE THREAD

**Issue by swedishfrenchpress** [lightning-digital-entertainment/cashu-address#7]
Goal: I want to claim my cashu-address ecash tokens on my cashu wallet in my mobile device.

Problem: Cashu address displays the cash token as a text string. I would like to a QR code that I can scan and receive the ecash tokens to my mobile wallet.

Suggestion: Display a QR code above when claiming sats.

What do you think @Egge21M?

![Frame 5802](https://github.com/lightning-digital-entertainment/cashu-address/assets/78821053/6751fa1e-7fb3-424c-9d60-8b03dd9036b9)

**Comment by Egge21M** [comment]
Hey, thanks for opening this issue! Definitely agree here, which is why I started working on bringing animated QR codes to the web with https://github.com/lightning-digital-entertainment/ur-wasm-js.

However this repo is for the protocol and reference implementation of the cashu-address service. Could you please reopen this issue at https://github.com/lightning-digital-entertainment/cashu-address-website ?
